version: '3.8'

services:
  builder:
    image: flutter/flutter:stable
    volumes:
      - ./lamoda_seller:/app
    working_dir: /app
    command: flutter build web --release

  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./lamoda_seller/build/web:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - builder